
<form method="post" action="/usuarios/salvar">
    <input type="hidden" name="id" value="<?php echo $user->id ?? '' ?>"/>

    <label>Nome</label><br/>
    <input type="text" name="nome" value="<?php echo $user->nome ?? ''; ?>" required/>

    <br/>

    <label>Email</label><br/>
    <input type="email" name="email" value="<?php echo $user->email ?? ''; ?>" required/>

    <br/>

    <label>Senha</label><br/>
    <input type="password" name="password" value="<?php echo $user->password ?? ''; ?>"/>

    <br/>
    <br/>

    <a href="/usuarios/lista">Voltar à lista</a>
    <button type="submit">
        Salvar
    </button>

</form>